release-date = "2023-03-22"

[[entries]]
id = "fa30746d-8ef3-4361-8c7d-774bf4141ff7"
type = "improvement"
description = "Explain how to show kraken's help"
author = "Nicolas Trinquier <trinquier.nico@gmail.com>"

[[entries]]
id = "36f9c99b-9927-4355-b8e5-ee14f64fccdc"
type = "fix"
description = "Require Python `>=3.7,<3.11` instead of `^3.7` due to Dill incompatibility (see https://github.com/kraken-build/kraken-wrapper/issues/4)"
author = "@NiklasRosenstein"
